[package]
name = "static-files-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static-files = "0.2.3"

[build-dependencies]
static-files = "0.2.3"
