[package]
name = "ssh-key-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
pem = "2.0.0"
sha2 = "0.10.6"
ssh-key = "0.5.1"
derp = "0.0.14"
untrusted = "0.7.0"
