[package]
name = "features"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
default = ["something", "bajja"] # Features are disabled by default
something = []
doit = []
bajja = []
all = ["something", "doit"]
