[package]
name = "binaryen-example"
version = "0.1.0"
edition = "2021"

[dependencies]
binaryen-sys = "0.13.0"

[[bin]]
name = "basic"
path = "src/main.rs"

[[bin]]
name = "update"
path = "src/update.rs"

[workspace]
